#!/usr/bin/env bash

set -e

if [[ "${GH_ACTIONS:-}" != "true" ]]; then
  echo "skipping git config since not on Github Actions"
  exit
fi

# git config --global user.email "149658+cloudgraph-cli@users.noreply.github.com"
# git config --global user.name "cloudgraph-cli"

git config --global user.email "no-reply@autocloud.dev"
git config --global user.name "autocloud-deploy-bot"
